[package]
name = "enginar"
authors = ["Burak Selim Senyurt"]
description = "Basit state tabanl覺 bir oyun motoru yazmaya kalksak temelleri nas覺l atard覺k sorusuna cevap ar覺yoruz."
version = "0.1.0"
edition = "2021"

[dependencies]
